name: toast_note
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.3
  http: ^1.2.1
  flutter_slidable: ^3.1.0
  provider: ^6.1.2
  font_awesome_flutter: ^10.8.0
  flutter_quill: ^10.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: alimama
      fonts:
        - asset: assets/fonts/AlimamaShuHeiTi-Bold.ttf